### ISSUE TITLE
为什么公式渲染还是错的啊

### ISSUE THREAD

**Issue by BuLiangRenDarkStar** [wherelse/gridea-theme-phantom#1]
“$C(p+\Delta p) \approx C(p) + \nabla _p C(p)*\Delta p = 0$”
Gridea 侧边的预览是正确的
![image](https://user-images.githubusercontent.com/20518266/235426737-6fc7f299-2c76-406b-ab04-877c03e9b21a.png)
但是浏览器上显示
![image](https://user-images.githubusercontent.com/20518266/235426785-b4c5ab26-4dab-4c2a-8959-431668d0ac0a.png)
查看 html 有多余的 “katex-html”，我要怎么删除？？

**Comment by wherelse** [comment]
我晚上看一下，可能有些小bug

**Comment by BuLiangRenDarkStar** [comment]
不用了，当时以为直接拷贝到主题目录会自动更新主题，没有选择主题。。。。。不好意思。。。&nbsp;


方少
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月1日(星期一) 下午4:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wherelse/gridea-theme-phantom] 为什么公式渲染还是错的啊 (Issue #1)





 
我晚上看一下，可能有些小bug
